import { type FormTemplate, pollinationsCover } from "./types";

const cover = (p: string) => pollinationsCover(p, 600, 400);

export const FORM_TEMPLATES: FormTemplate[] = [
  {
    slug: "solicitar-cotacao-completa",
    title: "Solicitar Cotação Completa",
    description: "Form rico com 8 campos pra leads B2B qualificados.",
    category: "cotacao",
    cover_url: cover("contact form quote request business B2B Brazil professional"),
    preset: {
      slug: "solicitar-cotacao-completa",
      title: "Solicitar cotação Spotlog",
      description: "Conta pra gente seu cenário. Em até 1 dia útil, um especialista monta a proposta.",
      submit_label: "Solicitar cotação",
      success_title: "Recebemos sua solicitação!",
      success_message: "Nosso comercial entra em contato em até 1 dia útil pelo e-mail e WhatsApp.",
      lead_source_detail: "cotacao-completa",
      fields: [
        { field_key: "full_name", type: "text", label: "Nome completo", placeholder: "Como devemos te chamar?", required: true, width: "half", maps_to_lead: "full_name" },
        { field_key: "email", type: "email", label: "E-mail corporativo", placeholder: "voce@empresa.com.br", required: true, width: "half", maps_to_lead: "email" },
        { field_key: "whatsapp", type: "phone", label: "WhatsApp", placeholder: "(11) 99999-9999", required: true, width: "half", maps_to_lead: "whatsapp" },
        { field_key: "company_name", type: "text", label: "Empresa", placeholder: "Nome da empresa", required: true, width: "half", maps_to_lead: "company_name" },
        { field_key: "segment", type: "select", label: "Segmento", required: true, width: "half",
          options: [
            { value: "ecommerce", label: "E-commerce" },
            { value: "farma", label: "Farmácia / Drogaria" },
            { value: "manipulacao", label: "Manipulação" },
            { value: "b2b", label: "B2B / Indústria" },
            { value: "outro", label: "Outro" },
          ],
        },
        { field_key: "volume", type: "select", label: "Volume mensal", required: true, width: "half",
          options: [
            { value: "ate_50", label: "Até 50/mês" },
            { value: "50_200", label: "50–200/mês" },
            { value: "200_500", label: "200–500/mês" },
            { value: "500_1000", label: "500–1.000/mês" },
            { value: "mais_1000", label: "Mais de 1.000/mês" },
          ],
        },
        { field_key: "regiao", type: "text", label: "Região de atuação", placeholder: "Ex: São Paulo capital, Grande SP", required: false, width: "full" },
        { field_key: "message", type: "textarea", label: "Conta um pouco do desafio", placeholder: "Como podemos ajudar?", required: true, width: "full", maps_to_lead: "message" },
      ],
    },
  },
  {
    slug: "agendar-demo",
    title: "Agendar Demonstração",
    description: "Form com data preferencial pra agendamento de demo/reunião.",
    category: "agenda",
    cover_url: cover("calendar booking demo schedule meeting professional"),
    preset: {
      slug: "agendar-demo",
      title: "Agendar uma demo Spotlog",
      description: "Escolha um dia, e nossa equipe confirma o horário em até 2 horas.",
      submit_label: "Quero agendar",
      success_title: "Agendamento solicitado!",
      success_message: "Vamos confirmar o horário pelo WhatsApp em até 2 horas.",
      lead_source_detail: "demo",
      fields: [
        { field_key: "full_name", type: "text", label: "Nome", required: true, width: "half", maps_to_lead: "full_name" },
        { field_key: "email", type: "email", label: "E-mail", required: true, width: "half", maps_to_lead: "email" },
        { field_key: "whatsapp", type: "phone", label: "WhatsApp", required: true, width: "half", maps_to_lead: "whatsapp" },
        { field_key: "company_name", type: "text", label: "Empresa", required: true, width: "half", maps_to_lead: "company_name" },
        { field_key: "datetime_slot", type: "date", label: "Data preferencial", required: true, width: "full" },
      ],
    },
  },
  {
    slug: "baixar-ebook",
    title: "Baixar Ebook",
    description: "Form mínimo pra download de lead magnet.",
    category: "captura",
    cover_url: cover("ebook download form simple minimal professional"),
    preset: {
      slug: "baixar-ebook",
      title: "Baixar ebook gratuito",
      description: "Preencha pra receber o link de download no e-mail.",
      submit_label: "Receber ebook",
      success_title: "Enviamos o ebook!",
      success_message: "Confira sua caixa de entrada — o link de download chegou agora.",
      lead_source_detail: "ebook",
      fields: [
        { field_key: "full_name", type: "text", label: "Nome", required: true, width: "full", maps_to_lead: "full_name" },
        { field_key: "email", type: "email", label: "E-mail", required: true, width: "full", maps_to_lead: "email" },
        { field_key: "company_name", type: "text", label: "Empresa", required: false, width: "full", maps_to_lead: "company_name" },
      ],
    },
  },
  {
    slug: "newsletter-blog",
    title: "Newsletter do Blog",
    description: "Inscrição ultra-simples pra newsletter semanal.",
    category: "newsletter",
    cover_url: cover("newsletter signup email subscribe simple minimal"),
    preset: {
      slug: "newsletter-blog",
      title: "Newsletter Spotlog",
      description: "Toda terça, dicas práticas de logística no seu e-mail.",
      submit_label: "Inscrever",
      success_title: "Inscrição confirmada!",
      success_message: "Primeira edição chega na próxima terça-feira.",
      lead_source_detail: "newsletter",
      fields: [
        { field_key: "full_name", type: "text", label: "Nome", required: true, width: "half", maps_to_lead: "full_name" },
        { field_key: "email", type: "email", label: "E-mail", required: true, width: "half", maps_to_lead: "email" },
      ],
    },
  },
  {
    slug: "abrir-conta-cliente",
    title: "Abrir Conta de Cliente",
    description: "Form completo de onboarding com 12 campos pra novo cliente.",
    category: "cotacao",
    cover_url: cover("client onboarding form complete business signup professional"),
    preset: {
      slug: "abrir-conta-cliente",
      title: "Abrir conta na Spotlog",
      description: "Preencha os dados pra criação imediata da sua conta na plataforma.",
      submit_label: "Criar conta",
      success_title: "Conta solicitada!",
      success_message: "Recebemos seus dados. Em até 4 horas você recebe o acesso por e-mail.",
      lead_source_detail: "abrir-conta",
      fields: [
        { field_key: "full_name", type: "text", label: "Responsável", required: true, width: "half", maps_to_lead: "full_name" },
        { field_key: "email", type: "email", label: "E-mail", required: true, width: "half", maps_to_lead: "email" },
        { field_key: "whatsapp", type: "phone", label: "WhatsApp", required: true, width: "half", maps_to_lead: "whatsapp" },
        { field_key: "cargo", type: "text", label: "Cargo", required: false, width: "half" },
        { field_key: "company_name", type: "text", label: "Razão social", required: true, width: "half", maps_to_lead: "company_name" },
        { field_key: "cnpj", type: "text", label: "CNPJ", placeholder: "00.000.000/0000-00", required: true, width: "half" },
        { field_key: "endereco", type: "text", label: "Endereço completo", required: true, width: "full" },
        { field_key: "cidade", type: "text", label: "Cidade", required: true, width: "half" },
        { field_key: "uf", type: "text", label: "UF", required: true, width: "half" },
        { field_key: "segment", type: "select", label: "Segmento", required: true, width: "half",
          options: [
            { value: "ecommerce", label: "E-commerce" },
            { value: "farma", label: "Farma" },
            { value: "b2b", label: "B2B / Indústria" },
            { value: "outro", label: "Outro" },
          ],
        },
        { field_key: "volume_mensal", type: "number", label: "Volume mensal esperado", required: false, width: "half" },
        { field_key: "obs", type: "textarea", label: "Observações", required: false, width: "full", maps_to_lead: "message" },
      ],
    },
  },
  {
    slug: "feedback-nps",
    title: "Pesquisa NPS",
    description: "Escala 0–10 + comentário pra medir satisfação.",
    category: "feedback",
    cover_url: cover("NPS survey rating customer satisfaction professional"),
    preset: {
      slug: "feedback-nps",
      title: "Como foi sua experiência com a Spotlog?",
      description: "1 minuto. Sua nota ajuda a gente a melhorar.",
      submit_label: "Enviar feedback",
      success_title: "Obrigado!",
      success_message: "Sua nota faz diferença. Bora seguir melhorando.",
      lead_source_detail: "nps",
      fields: [
        { field_key: "nota", type: "select", label: "De 0 a 10, quanto recomendaria?", required: true, width: "full",
          options: Array.from({ length: 11 }, (_, i) => ({ value: String(i), label: String(i) })),
        },
        { field_key: "comentario", type: "textarea", label: "Conta o que pesou na sua nota", placeholder: "O que foi bom? O que podia melhorar?", required: false, width: "full" },
        { field_key: "email", type: "email", label: "E-mail (opcional, pra retorno)", required: false, width: "full", maps_to_lead: "email" },
      ],
    },
  },
];

export function findFormTemplate(slug: string): FormTemplate | undefined {
  return FORM_TEMPLATES.find((t) => t.slug === slug);
}
